"""Add collected_at to Evidence

Revision ID: 0423858f2e1e
Revises: 35ce4aaea567
Create Date: 2025-12-11 10:22:29.085947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0423858f2e1e'
down_revision = '35ce4aaea567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collected_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_column('collected_at')

    # ### end Alembic commands ###
