"""Detailed Case Schemas

Revision ID: 35ce4aaea567
Revises: d6153aa8589c
Create Date: 2025-12-11 02:04:21.406740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ce4aaea567'
down_revision = 'd6153aa8589c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidentiality_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('related_case_ids', sa.Text(), nullable=True))

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('national_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('consent_for_contact', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('consent_for_contact')
        batch_op.drop_column('status')
        batch_op.drop_column('national_id')
        batch_op.drop_column('address')
        batch_op.drop_column('dob')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('related_case_ids')
        batch_op.drop_column('tags')
        batch_op.drop_column('confidentiality_level')

    # ### end Alembic commands ###
