"""Comprehensive Case Fields

Revision ID: d6153aa8589c
Revises: 65e3eb852d71
Create Date: 2025-12-11 01:40:35.582233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6153aa8589c'
down_revision = '65e3eb852d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_officers',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'user_id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offense_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('incident_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gps_coordinates', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_cognizable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ipc_sections', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('init_medical_exam', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('init_prelim_enquiry', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('init_scene_visit', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('init_scene_visit')
        batch_op.drop_column('init_prelim_enquiry')
        batch_op.drop_column('init_medical_exam')
        batch_op.drop_column('ipc_sections')
        batch_op.drop_column('is_cognizable')
        batch_op.drop_column('gps_coordinates')
        batch_op.drop_column('incident_date')
        batch_op.drop_column('short_description')
        batch_op.drop_column('offense_type')

    op.drop_table('participant')
    op.drop_table('case_officers')
    # ### end Alembic commands ###
